[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solanatemplate = "A76PhT8ccbTLi9wLHfEJrS4rr99zoU6vwDoQB3Q8FtiR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jl1013/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
